version: "3"
services:
  mysql:
    image: mysql #image:tag
    environment:
      - MYSQL_ROOT_PASSWORD= password
    ports:
      - "3306:3306" #left side- host port. right side- container port.
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql #db_data is on host machine, /var/lib/mysql is  the container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s #specifies the number of seconds to initially wait before executing the health check and then the frequency at which subsequent health checks will be performed.
      timeout: 5s #specifies the number of seconds Docker awaits for your health check command to return an exit code before declaring it as failed.
      retries: 3 #specifies the number of consecutive health check failures required to declare the container as unhealthy.
    

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy    

  server:
    build: ./server #The service is built using the Dockerfile located in the ./server
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    


  worker:
    build: ./worker #The service is built using the Dockerfile located in the ./worker
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      server:
        condition: service_started
    

  client:
    build: ./client #The service is built using the Dockerfile located in the ./client
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      server:
        condition: service_started    
      worker:
        condition: service_started 


volumes:
  db_data:
  redis_data:



